### ISSUE TITLE
Re-organize location of splines functions

### ISSUE THREAD

**Issue by kristelizq** [Bramson-Planetary-Research-Group/Mars-Troughs#13]
It is tricky to differentiate between what ret_spline, get_Rt_model and get_retreat functions do. The location of each function can be changed to make it easier for the user to understand the logic behind. The names of the function can be changed too to make it easier to differentiate them. Adding details to the docstrings would also help understand what the functions are doing.

**Comment by tmcclintock** [comment]
@kristelizq is this issue now solved as well?
